language: python
branches:
        only:
                master
before_install:
- openssl aes-256-cbc -K $encrypted_88a0b20be284_key -iv $encrypted_88a0b20be284_iv
  -in publish-key.enc -out publish-key -d
- chmod u=rw,og= publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile publish-key" >> ~/.ssh/config
- git --version
- git remote set-url origin git@github.com:johnveitch/cpnest.git
install:
- pip install cpnest ghp-import sphinx sphinx-rtd-theme
cache:
 directories:
  - .env
script:
- cd docs
- make html
- ghp-import _build/html/ -pf

