language: python
branches:
        only:
                master
before_install:
- openssl aes-256-cbc -K $encrypted_88a0b20be284_key -iv $encrypted_88a0b20be284_iv
  -in publish-key.enc -out publish-key -d
install:
- pip install cpnest
script:
- python setup.py build_sphinx -b html

